from pathlib import Path
from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    import pytest


class ProtocolTest(Protocol):
    @property
    def setup_test(self, tmp_path: Path) -> None: ...
    def _setup(self) -> None: ...
    def _teardown(self) -> None: ...
    def get_test_file_path(self, filename: str) -> Path: ...


class ProtocolTestAsync(ProtocolTest, Protocol):
    @property
    def setup_async_test(self) -> None: ...


class ProtocolTestIntegration(ProtocolTest, Protocol):
    @property
    def setup_integration_test(self) -> None: ...
    def _setup_services(self) -> None: ...
    def _cleanup_services(self) -> None: ...


class ProtocolTestAPI(ProtocolTest, Protocol):
    @property
    def setup_api_test(self) -> None: ...
    def _create_test_client(self): ...
    def _cleanup_test_client(self): ...
    def get(self, url: str, **kwargs): ...
    def post(self, url: str, **kwargs): ...
    def put(self, url: str, **kwargs): ...
    def delete(self, url: str, **kwargs): ...
