from typing import Protocol
from src.omnibase.enums.enum_validation_result import EnumValidationResult
from src.omnibase.enums.enum_validation_type import EnumValidationType
from omnibase.nodes.node_parity_validator.v1_0_0.models.state import DiscoveredNode

class ProtocolNodeValidationTool(Protocol):
    def validate_cli_node_parity(self, node: DiscoveredNode) -> EnumValidationResult: ...
    def validate_schema_conformance(self, node: DiscoveredNode) -> EnumValidationResult: ...
    def validate_error_code_usage(self, node: DiscoveredNode) -> EnumValidationResult: ...
    def validate_contract_compliance(self, node: DiscoveredNode) -> EnumValidationResult: ...
    def validate_introspection_validity(self, node: DiscoveredNode) -> EnumValidationResult: ... 