[tool.poetry]
name = "{service_name}"
version = "0.1.0"
description = "{Service description}"
authors = ["Jonah Gabriel"]
readme = "README.md"
packages = [{include = "{service_name}", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
# Common dependencies for all services
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
pydantic = "^2.6.0"
pydantic-settings = "^2.1.0"
redis = "^5.0.0"
requests = "^2.31.0"

# Optional dependencies (uncomment as needed)
# Database dependencies
# sqlalchemy = "^2.0.0"
# psycopg2-binary = "^2.9.9"
# asyncpg = "^0.29.0"

# Monitoring dependencies
# psutil = "^5.9.8"
# prometheus-client = "^0.19.0"

# File handling dependencies
# aiofiles = "^23.2.0"
# watchdog = "^3.0.0"

[tool.poetry.group.dev.dependencies]
# Testing
pytest = "^8.0.0"
pytest-asyncio = "^0.23.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
pytest-timeout = "^2.2.0"

# Code quality
black = "^24.1.0"
isort = "^5.13.0"
flake8 = "^7.0.0"
mypy = "^1.8.0"

# Development utilities
httpx = "^0.27.0"  # For testing FastAPI applications

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
asyncio_mode = "auto"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning"
]

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
