# MkDocs configuration for OmniBase docs
site_name: OmniBase Documentation
nav:
  - Home: index.md
  - Getting Started: guides/getting_started.md
  - CLI Quickstart: guides/cli_quickstart.md
  - Specs: specs/omnibase_design_spec.md
  - Architecture:
      - Repository Structure: architecture/repository_structure.md
      - Registry Backend Choices: architecture/registry_backend_choices.md
  - RFCs: rfcs/rfc-0001-async-execution.md
  - ADRs: adr/0001-protocol_vs_abc.md
  - Security: security/threat_model.md
  - Reviews: reviews/2025-05-15_system_architect.md
  - Changelogs: changelogs/RELEASE_NOTES.md
