config:
  scenario_config_version: "1.0.0"
  registry_tools: {}

chain:
  - node: node_manager
    input:
      cli_action: "generate"
      command_name: "generate"
      args:
        - "--custom-config"
    expect:
      status: "success"
      cli_command: "generate --custom-config"
      errors: [] 