# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated from contract.yaml
# To regenerate: run the node_manager codegen orchestrator.

from enum import Enum

class NodeKafkaEventBusNodeErrorCode(Enum):
    BACKEND_UNAVAILABLE = 'BACKEND_UNAVAILABLE'
    CONNECTION_FAILED = 'CONNECTION_FAILED'
    MESSAGE_PUBLISH_FAILED = 'MESSAGE_PUBLISH_FAILED'
    MESSAGE_CONSUME_FAILED = 'MESSAGE_CONSUME_FAILED'
    TIMEOUT_EXCEEDED = 'TIMEOUT_EXCEEDED'
    CONFIGURATION_ERROR = 'CONFIGURATION_ERROR'
    HANDLER_NOT_FOUND = 'HANDLER_NOT_FOUND'
    BOOTSTRAP_FAILED = 'BOOTSTRAP_FAILED'
    INTEGRATION_ERROR = 'INTEGRATION_ERROR'
    RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED'
