# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated from contract.yaml
# contract_hash: 71a46cf39e20dcccdf78ddf4572b59851df4fba673b2ceca90d8cb7cbf3cf513
# To regenerate: poetry run python src/omnibase/runtimes/onex_runtime/v1_0_0/codegen/contract_to_model.py --contract src/omnibase/nodes/node_kafka_event_bus/v1_0_0/contract.yaml --output-dir src/omnibase/nodes/node_kafka_event_bus/v1_0_0/models

from enum import Enum

class NodeKafkaEventBusNodeErrorCode(Enum):
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    INVALID_PARAMETER = 'INVALID_PARAMETER'
    MISSING_REQUIRED_PARAMETER = 'MISSING_REQUIRED_PARAMETER'
    SCHEMA_VALIDATION_FAILED = 'SCHEMA_VALIDATION_FAILED'
    UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION'
    BACKEND_UNAVAILABLE = 'BACKEND_UNAVAILABLE'
    CONNECTION_FAILED = 'CONNECTION_FAILED'
    MESSAGE_PUBLISH_FAILED = 'MESSAGE_PUBLISH_FAILED'
    MESSAGE_CONSUME_FAILED = 'MESSAGE_CONSUME_FAILED'
    TIMEOUT_EXCEEDED = 'TIMEOUT_EXCEEDED'
    CONFIGURATION_ERROR = 'CONFIGURATION_ERROR'
    HANDLER_NOT_FOUND = 'HANDLER_NOT_FOUND'
    BOOTSTRAP_FAILED = 'BOOTSTRAP_FAILED'
    INTEGRATION_ERROR = 'INTEGRATION_ERROR'
    RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED'
