from enum import Enum


class TemplateErrorCode(Enum):
    UNKNOWN_ERROR = 0
    INVALID_PARAMETER = 1
    MISSING_REQUIRED_PARAMETER = 2
    SCHEMA_VALIDATION_FAILED = 3
    UNSUPPORTED_OPERATION = 4
